version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # ports:
    #   - 5555:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: parksangmin
      POSTGRES_DB: parksangmin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    image: flask
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5101:5101
    volumes:
      - ${PWD}:/usr/src/app
    links:
      - "db:database"
    command: python3 -m flask --app user.user run --port 5101 --host 0.0.0.0
