name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  data-extract-cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and release to DockerHub
    env:
      REGISTRY: jigeria
      REPOSITORY: practice_msa
      IMAGE_TAG: ${{ github.sha }}
    run: |
      docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
      docker push $REGISTRY/$REPOSITORY:latest
      docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
